CREATE DATABASE FOCUSTRACKER;

CREATE TABLE USUARIO(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	EMAIL VARCHAR(100) NOT NULL,
	SENHA VARCHAR(50) NOT NULL,
	TOKEN VARCHAR(20),
	EXPIRATION DATETIME,
	NOME VARCHAR(500) NOT NULL,
	DTNASC DATE NOT NULL,
	CEP VARCHAR(10) NOT NULL
);

ALTER TABLE `USUARIO` ADD UNIQUE INDEX(`EMAIL`);