CREATE DATABASE FOCUSTRACKER;

CREATE TABLE USUARIO(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	EMAIL VARCHAR(100) NOT NULL,
	SENHA VARCHAR(50) NOT NULL,
	TOKEN VARCHAR(20),
	EXPIRATION DATETIME,
	NOME VARCHAR(500) NOT NULL,
	DTNASC DATE NOT NULL,
	CEP VARCHAR(10) NOT NULL
);

ALTER TABLE `USUARIO` ADD UNIQUE INDEX(`EMAIL`);

CREATE TABLE DOENCA(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(30),
	FOCO BOOLEAN NOT NULL DEFAULT 0
);

INSERT INTO DOENCA (NOME) VALUES ('Corona Vírus');
INSERT INTO DOENCA (NOME) VALUES ('Dengue');
INSERT INTO DOENCA (NOME) VALUES ('Zika');
INSERT INTO DOENCA (NOME, FOCO) VALUES ('Foco Dengue', 1);

CREATE TABLE BAIRRO (
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	NOME VARCHAR(500),
	CEP_INICIAL VARCHAR(10),
	CEP_FINAL VARCHAR(10)
)

CREATE TABLE CASO(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	DOENCA INT NOT NULL,
	CONFIRMADO BOOLEAN NOT NULL DEFAULT 0,
	DESCARTADO BOOLEAN NOT NULL DEFAULT 0,
	CURADO BOOLEAN NOT NULL DEFAULT 0,
	OBITO BOOLEAN NOT NULL DEFAULT 0,
	OBSERVACAO VARCHAR(500),
	LATITUDE NUMERIC,
	LONGITUDE NUMERIC,
	BAIRRO INT NOT NULL,
	FOREIGN KEY (DOENCA) REFERENCES DOENCA(ID),
	FOREIGN KEY (BAIRRO) REFERENCES BAIRRO(ID)
);
